config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :clients
  resources :services
  resources :fees
  resources :jobs
  resources :boards

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :jobs
  has_many :services
  has_many :fees
  has_many :users

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :jobs
  has_many :users

end

app/models/fee.rb
class Fee < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :client
  belongs_to :board
  has_many :fees
  has_many :services
  PAYMENTTYPES = ['Cash', 'Credit']
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :jobs
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  # returns the hash digest of the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Return a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remember a user in the db for use in persisten sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forget a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_filter :authenticate

  def index
    @jobs = Job.all
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate
  def index
    @clients = Client.all
  end
  def new
    @client = Client.new
  end

  def show
    @clients = Client.all
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    if @client.update(client_params)
      redirect_to @client
    else
      render 'edit'
    end
  end

  def create
    @client = Client.new(client_params)
    @client.save
    flash[:success] = "Account created!"
    redirect_to clients_path
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_path
  end
end

private

def client_find
  @client = current_user.client.find(params[:id])
end

def client_params
  params.require(:client).permit(:client_name, :client_streetaddress, :client_floor, :client_email, :client_phone, :client_specialinstructions)
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
    before_filter :authenticate

    def index
    end

    def new
      @fee = Fee.new
    end

    def show
      @fee = Fee.all
    end

    def edit
      @fee = Fee.find(params[:id])
    end

    def update
      @fee = Fee.find(params[:id])

      if @fee.update(fee_params)
        redirect_to @fee
      else
        render 'edit'
      end
    end

    def create
      @fee = Fee.new(fee_params)
      @fee.save
      flash[:success] = "Service created!"
      redirect_to fees_path
    end

    def destroy
      @fee = Fee.find(params[:id])
      @fee.destroy
      redirect_to fees_path
    end
  end

  private

  def fee_find
    @fee = current_user.fee.find(params[:id])
  end

  def fee_params
    params.require(:fee).permit(:fee_name, :fee_price, :fee_category, :fee_notes)
  end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate
  def index
  end

  def new
    @job = Job.new
  end

  def show
    @jobs = Job.all
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to @job
    else
      render 'edit'
    end
  end

  def create
    @job = Job.new(job_params)
    @job.save
    flash[:success] = "Job created!"
    redirect_to jobs_path
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end
end

private

def job_find
  @job = current_user.job.find(params[:id])
end

def job_params
  params.require(:job).permit(:job_client, :job_originaddress, :job_destinationaddress, :job_servicelevel, :job_orderplacer, :job_orderphone, :job_orderemail, :job_billingreference,
                              :job_datetime, :job_price, :job_oversize, :job_overweight, :job_waittime, :job_misc)
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate

  def index
  end

  def new
    @service = Service.new
  end

  def show
    @services = Service.all
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])

    if @service.update(service_params)
      redirect_to @service
    else
      render 'edit'
    end
  end

  def create
    @service = Service.new(service_params)
    @service.save
    flash[:success] = "Service created!"
    redirect_to services_path
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to services_path
  end
end

private

def service_find
  @service = current_user.service.find(params[:id])
end

def service_params
  params.require(:service).permit(:service_name, :service_baseprice, :service_duetime, :service_notes)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Dispatchers App!"
      redirect_to @user
    else
      render 'new'
    end
  end
end

private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Log in the given user (below)
  def log_in(user)
    session[:user_id] = user.id
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Remembers a user in a persisten session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Return the current logged in user if there is one
  def current_user
    if (user_id = session[:user_id])
    @current_user ||= User.find_by(id: user_id)
  elsif (user_id = cookies.signed[:user_id])
    user = User.find_by(id: user_id)
    if user && user.authenticated?(cookies[:remember_token])
      log_in user
      @current_user = user
   end
 end
end

def logged_in?
  !current_user.nil?
end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def authenticate
    if !logged_in?
      redirect_to root_path
    end
  end
end

app/views/boards/index.html.erb
<div class="container">
  <h1>Dispatch Board</h1>
  <hr>
  <div class="dispatch-table">
  <table class="table table-striped table hover">
    <tr>
      <th>Rider/Driver</th>
      <th>Origin Address</th>
      <th>Destination Address</th>
      <th>Service Level</th>
    </tr>
    <% @jobs.each do |job| %>
    <tr>
    <td>
      
    </td>
    <td><%= job.job_originaddress %></td>
    <td><%= job.job_destinationaddress %></td>
    <td><%= job.job_servicelevel %></td>
    </tr>
    <% end %>
  </table>
</div>
</div>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@client) do |form| %>

    <%= form.label :client_name, "Client Name" %>
    <%= form.text_field :client_name %>

    <%= form.label :client_streetaddress, "Street Address" %>
    <%= form.text_field :client_streetaddress %>

    <%= form.label :client_floor, "Floor / Suite / Apt #" %>
    <%= form.text_field :client_floor %>

    <%= form.label :client_email, "Email" %>
    <%= form.email_field :client_email %>

    <%= form.label :client_phone, "Phone number" %>
    <%= form.text_field :client_phone %>

    <%= form.label :client_specialinstructions, "Special instructions" %>
    <%= form.text_area :client_specialinstructions %>

    <%= form.submit "Edit account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/clients/index.html.erb
<%= link_to "Add Client", new_client_path, class: "btn btn-primary" %>
<%= link_to "Find Client", client_path(:id), class: "btn btn-primary" %>
<h1>Clients</h1>
<table class="table table-striped table-hover"id="clients">
  <tr>
    <th>Client name</th>
    <th>Client address</th>
    <th>Client floor</th>
    <th>Client email</th>
    <th>Client phone</th>
    <th>Special instructions</th>
    <th>Edit | Delete</th>
  </tr>

  <% @clients.each do |client| %>
    <tr>
      <td><%= client.client_name %></td>
      <td><%= client.client_streetaddress %></td>
      <td><%= client.client_floor %></td>
      <td><%= client.client_email %></td>
      <td><%= client.client_phone %></td>
      <td><%= client.client_specialinstructions %></td>
      <td><%= link_to "Edit", edit_client_path(client), class: "btn-xs btn-info" %>&nbsp;
      |&nbsp;<%= link_to "Delete", client_path(client), class: "btn-xs btn-info",
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
</table>

app/views/clients/new.html.erb
<div class="container">
  <h1>Create New Client</h1>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <%= bootstrap_form_for(@client) do |form| %>

        <%= form.label :client_name, "Client Name" %>
        <%= form.text_field :client_name, hide_label: true %>

        <%= form.label :client_streetaddress, "Street Address" %>
        <%= form.text_field :client_streetaddress, hide_label: true %>

        <%= form.label :client_floor, "Floor / Suite / Apt #" %>
        <%= form.text_field :client_floor, hide_label: true %>

        <%= form.label :client_email, "Email" %>
        <%= form.email_field :client_email, hide_label: true %>

        <%= form.label :client_phone, "Phone number" %>
        <%= form.text_field :client_phone, hide_label: true %>

        <%= form.label :client_specialinstructions, "Special instructions" %>
        <%= form.text_area :client_specialinstructions, hide_label: true, style: "resize:none" %>

        <%= form.submit "Create account", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>

app/views/clients/show.html.erb
<%= link_to "Add Client", new_client_path, class: "btn btn-primary" %>
<%= link_to "Find Client", client_path(:id), class: "btn btn-primary" %>
<h1>Clients</h1>
<div class="container">
<table>
  <tr>
    <th>Client name</th>
    <th>Client address</th>
    <th>Client floor</th>
    <th>Client email</th>
    <th>Client phone</th>
    <th>Special instructions</th>
  </tr>

  <% @clients.each do |client| %>
    <tr>
      <td><%= client.client_name %></td>
      <td><%= client.client_streetaddress %></td>
      <td><%= client.client_floor %></td>
      <td><%= client.client_email %></td>
      <td><%= client.client_phone %></td>
      <td><%= client.client_specialinstructions %></td>
      <td><%= link_to "Edit", edit_client_path(client), class: "btn-xs btn-info" %>&nbsp;</td>
      <td>|&nbsp;<%= link_to "Delete", client_path(client), class: "btn-xs btn-info",
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
</table>
</div>

app/views/fees/edit.html.erb
<div class="container">
  <h1>Edit Fee</h1>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= bootstrap_form_for(@fee) do |form| %>

        <%= form.label :fee_name, "Fee name:" %>
        <%= form.text_field :fee_name, hide_label: true %>

        <%= form.label :fee_price, "Fee price:" %>
        <%= form.text_field :fee_price, hide_label: true %>

        <%= form.label :fee_category, "Fee Category:" %> (for example : "overweight" charge)
        <%= form.text_field :fee_category, hide_label: true %>

        <%= form.label :fee_notes, "Fee notes:" %>
        <%= form.text_area :fee_notes, hide_label: true, style: "resize:none" %>

        <%= form.submit "Edit Fee", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>

app/views/fees/index.html.erb
<%= link_to "Create fee", new_fee_path, class: "btn btn-primary" %>
<%= link_to "Fees", fee_path(:id), class: "btn btn-primary" %>
<h1>Fees</h1>

app/views/fees/new.html.erb
<div class="container">
  <h1>Create Fee</h1>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= bootstrap_form_for(@fee) do |form| %>

        <%= form.label :fee_name, "Fee name:" %>
        <%= form.text_field :fee_name, hide_label: true %>

        <%= form.label :fee_price, "Fee price:" %>
        <%= form.text_field :fee_price, hide_label: true %>

        <%= form.label :fee_category, "Fee Category:" %> (for example : "overweight" charge)
        <%= form.text_field :fee_category, hide_label: true %>

        <%= form.label :fee_notes, "Fee notes:" %>
        <%= form.text_area :fee_notes, hide_label: true, style: "resize:none" %>

        <%= form.submit "Create Fee", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/fees/show.html.erb
<h1>Fees</h1>
<div class="container">
<table class="table table-striped table-hover">
  <tr>
    <th>Fee Name</th>
    <th>Fee Price ($)</th>
    <th>Fee Category</th>
    <th>Notes</th>
    <th>Edit | Delete</th>
  </tr>

  <% @fee.each do |fee| %>
    <tr>
      <td><%= fee.fee_name %></td>
      <td><%= number_to_currency(fee.fee_price) %></td>
      <td><%= fee.fee_category %></td>
      <td><%= fee.fee_notes %></td>
      <td><%= link_to "Edit", edit_fee_path(fee), class: "btn-xs btn-info" %>&nbsp;
      |&nbsp;<%= link_to "Delete", fee_path(fee), class: "btn-xs btn-info",
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
</table>
</div>

app/views/homes/index.html.erb
<div class="container">
  <h1>Gem</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <% if logged_in? %>
        Welcome to Gem Dispatch.
      <% else %>
        <%= link_to "Courier Log In", new_session_path, class: "btn btn-primary" %>
        <%= link_to "Client Log In", "#", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>

app/views/jobs/edit.html.erb
<%= link_to "Add Job", new_job_path, class: "btn btn-primary" %>
<%= link_to "Find Job", job_path(:id), class: "btn btn-primary" %>
<h1>Jobs</h1>
<div class="container">
<table>
  <tr>
    <th>Client name</th>
    <th>Service Level</th>
    <th>Origin Address</th>
    <th>Destination Address</th>
    <th>Billing Reference</th>
    <th>Special instructions</th>
  </tr>

  <% @jobs.each do |job| %>
    <tr>
      <td><%= job.job_client %></td>
      <td><%= job.job_servicelevel %></td>
      <td><%= job.job_originaddress %></td>
      <td><%= job.job_destinationaddress %></td>
      <td><%= job.job_billingreference %></td>
      <td><%= job.job_specialinstructions %></td>
      <td><%= link_to "Edit", edit_job_path(job), class: "btn-xs btn-info" %>&nbsp;</td>
      <td>|&nbsp;<%= link_to "Delete", job_path(job), class: "btn-xs btn-info",
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
</table>
</div>

app/views/jobs/index.html.erb
<%= link_to "Add Job", new_job_path, class: "btn btn-primary" %>
<%= link_to "Find Job", job_path(:id), class: "btn btn-primary" %>
<h1>Jobs</h1>

app/views/jobs/new.html.erb
<div class="container">
  <h1>Create Job</h1>
    <div class="row">
      <div class="col-md-3">
        <%= bootstrap_form_for(@job) do |form| %>
          <h3>Job Information</h3>

          <%= form.label :job_client, "Client:" %>
          <%= collection_select( :job, :job_client, Client.all, :client_name, :client_name, {}, { :multiple => false}) %>

          <%= form.label :job_originaddress, "Origin address:" %>
          <%= form.text_field :job_originaddress, hide_label: true %>

          <%= form.label :job_destinationaddress, "Destination address:" %>
          <%= form.text_field :job_destinationaddress, hide_label: true %>

          <%= form.label :job_servicelevel, "Service level:" %>
          <%= collection_select( :job, :job_servicelevel, Service.all, :service_name, :service_name, {}, { :multiple => false}) %>

          <%= form.label :job_paymenttype, "Payment type:" %>
          <%= form.collection_select :job_paymenttype, Job::PAYMENTTYPES, :to_s, :to_s,
              :include_blank => true,
              hide_label: true %>

          <%= form.label :job_billingreference, "Billing reference:" %>
          <%= form.text_field :job_billingreference, hide_label: true %>

          <%= form.submit "Create job", class: "btn btn-primary" %>
      </div>
      <div class="col-md-3">
        <h3>Contact Information</h3>

        <%= form.label :job_orderplacer, "Order placer:" %>
        <%= form.text_field :job_orderplacer, hide_label: true %>

        <%= form.label :job_orderemail, "E-mail:" %>
        <%= form.text_field :job_orderemail, hide_label: true %>

        <%= form.label :job_orderphone, "Phone number:" %>
        <%= form.text_field :job_orderphone, hide_label: true %>

        <%= form.label :job_specialinstructions, "Special instructions:" %>
        <%= form.text_area :job_specialinstructions, hide_label: true, style: "resize:none" %>
      </div>
      <div class="col-sm-3">
        <h3> Date \ Time Ready</h3>
        <div class="form-group">
          <%= label_tag :job_datetime, 'Date \ time ready:' %>
          <div class="input-group date" id="datetimepicker">
            <%= text_field_tag :job_datetime, nil, class: 'form-control', data: { date_format: 'YYYY/MM/DD hh:mm A' } %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script>
$(function() {
  $('#datetimepicker').datetimepicker();
});
</script>

app/views/jobs/show.html.erb
<%= link_to "Add Job", new_job_path, class: "btn btn-primary" %>
<%= link_to "Find Job", job_path(:id), class: "btn btn-primary" %>
<h1>Jobs</h1>
<div class="container">
<table class="table table-striped table-hover">
  <tr>
    <th>Client name</th>
    <th>Service Level</th>
    <th>Origin Address</th>
    <th>Destination Address</th>
    <th>Billing Reference</th>
    <th>Special instructions</th>
  </tr>

  <% @jobs.each do |job| %>
    <tr>
      <td><%= job.job_client %></td>
      <td><%= job.job_servicelevel %></td>
      <td><%= job.job_originaddress %></td>
      <td><%= job.job_destinationaddress %></td>
      <td><%= job.job_billingreference %></td>
      <td><%= job.job_specialinstructions %></td>
      <td><%= link_to "Edit", edit_job_path(job), class: "btn-xs btn-info" %>&nbsp;</td>
      <td>|&nbsp;<%= link_to "Delete", job_path(job), class: "btn-xs btn-info",
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
</table>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand">
          <%= link_to "Gem", root_path, id: "logo" %>
        </div>
      </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Board", boards_path %></li>
        <li><%= link_to "Jobs", jobs_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Stuff <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Clients", clients_path %></li>
              <li><%= link_to "Service levels", services_path %></li>
              <li><%= link_to "Fees", fees_path %></li>
              <li><%= link_to "CSV export", "#" %></li>
            </ul>
          </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", "#" %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", session_path(:id), method: "delete" %></li>
          </li>
        </ul>
      </li>
      <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "Log in", new_session_path %></li>
     <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dispatchers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/services/edit.html.erb
<div class="container">
  <h1>Edit Service</h1>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= bootstrap_form_for(@service) do |form| %>

        <%= form.label :service_name, "Service name:" %>
        <%= form.text_field :service_name, hide_label: true %>

        <%= form.label :service_baseprice, "Base price:" %>
        <%= form.text_field :service_baseprice, hide_label: true %>

        <%= form.label :service_notes, "Service notes:" %>
        <%= form.text_area :service_notes, hide_label: true, style: "resize:none" %>

        <%= form.submit "Edit service", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/services/index.html.erb
<%= link_to "Create service", new_service_path, class: "btn btn-primary" %>
<%= link_to "Services", service_path(:id), class: "btn btn-primary" %>
<h1>Services</h1>

app/views/services/new.html.erb
<div class="container">
  <h1>Create Service</h1>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= bootstrap_form_for(@service) do |form| %>

        <%= form.label :service_name, "Service name:" %>
        <%= form.text_field :service_name, hide_label: true %>

        <%= form.label :service_baseprice, "Base price:" %>
        <%= form.text_field :service_baseprice, hide_label: true %>

        <%= form.label :service_notes, "Service notes:" %>
        <%= form.text_area :service_notes, hide_label: true, style: "resize:none" %>

        <%= form.submit "Create service", class: "btn btn-primary" %>
      <% end %>
    </div>
    </div class="col-md-4"></div>
  </div>
</div>

app/views/services/show.html.erb
<h1>Service Levels</h1>
<div class="container">
<table class="table table-striped table-hover">
  <tr>
    <th>Service Level</th>
    <th>Base Price ($)</th>
    <th>Service Time</th>
    <th>Notes</th>
    <th>Edit | Delete</th>
  </tr>

  <% @services.each do |service| %>
    <tr>
      <td><%= service.service_name %></td>
      <td><%= number_to_currency(service.service_baseprice) %></td>
      <td><%= service.service_duetime %></td>
      <td><%= service.service_notes %></td>
      <td><%= link_to "Edit", edit_service_path(service), class: "btn-xs btn-info" %>&nbsp;
      |&nbsp;<%= link_to "Delete", service_path(service), class: "btn-xs btn-info",
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
</table>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>
  </div>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |form| %>
    <%= render 'shared/error_messages' %>

    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>

    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>

    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>

    <%= form.label :password_confirmation, "Confirmation" %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>

    <%= form.submit "Create account", class: "btn btn-primary" %>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </div>